# Generated by Django 3.2.5 on 2021-09-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_auto_20210918_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balance',
            new_name='deposit',
        ),
    ]
