# Generated by Django 3.2.5 on 2021-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_rename_balance_balance_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
