# Generated by Django 3.2.5 on 2021-09-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0006_alter_balance_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(max_length=20),
        ),
    ]
