# Generated by Django 3.2.5 on 2021-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0007_alter_expense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
