# Generated by Django 3.2.5 on 2021-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_auto_20210921_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='deposit',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(max_length=10),
        ),
    ]
