# Generated by Django 3.2.5 on 2021-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0010_auto_20210921_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
